export const WEAPON_DISTANCE = 40;
export const WEAPON_ROTATION_SPD = 0.01;
export const WEAPON_45_CLOCKWISE_ROTATION = 3 / 4 * Math.PI;

export const SWORD_DEFAULT_COOLDOWN = 120;
export const SWORD_DEFAULT_ATTACKFRAME = 20;
export const SWORD_DEFAULT_POWER = 5
export const SWORD_SPECIAL_ATTACK_TIME = 120;
export const SWORD_SPECIAL_CHARGE_MAX = 10;
export const SWORD_SPECIAL_POWER_MULTIPLY = 20;

export const BASICGUN_DEFAULT_COOLDOWN = 40
export const BASICGUN_DEFAULT_POWER = 5
export const BASICGUN_INITIAL_ANGLE = 0;
export const BASICBULLET_DEFAULT_SPEED = 300;

export const FREEZEGUN_DEFAULT_COOLDOWN = 60
export const FREEZEGUN_DEFAULT_PERCENT = 0.6
export const FREEZEGUN_DEFAULT_DURATION = 60
export const FREEZEGUN_DEFAULT_RANGE = 30;
export const FREEZEBULLET_PARTICLE_NUM = 10;
export const FREEZEBULLET_PARTICLE_LIFE = 120;

export const ENEMY_DEFAULT_HP = 10;
export const ENEMY_DEFAULT_POWER = 5;
export const ENEMY_DEFAULT_SPEED = 20;
export const ENEMY_DEFAULT_DROP_CHANCE = 10;
export const ENEMY_FORMATATION_LIFE_SPAN = 100000;

export const PLAYER_DEFAULT_HP = 100;
export const PLAYER_DEFAULT_SPEED = 200;
export const PLAYER_HP_BAR_MAX_LENGTH = 500;

export const PICKUP_DEFAULT_LIFE = 600;
export const PICKUP_BLINK_START = 100;
export const PICKUP_BLINK_FREQUENT = 20;
export const PICKUP_DROP_ANIME_TIME = 20;

export const TROLL_POWER_DROP_THRESH = 33;
export const TROLL_SPEED_DROP_THRESH = 66;
export const TROLL_SPECIAL_DROP_THRESH = 100;

export const DMG_TEXT_LIFE_TIME = 30;

